# This is a basic workflow to help you get started with Actions

name: Hello World!

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]




# Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

